### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by tomyhu** [wjchen/AndroidUvcCameras#1]
你好!
 我想知道你的libv4ljni-common.so是怎么生成的，我还需要改动下面的代码，你能发份jni的代码给我吗？
我的邮箱是373974649@qq.com,非常感谢

**Comment by wjchen** [comment]
代码不提供。
可供参考： https://gist.github.com/maxlapshin/1253534
和 https://github.com/quanhua92/AndroidUsbCamera

**Comment by tomyhu** [comment]
那你能告诉我你用什么工具编译的吗？
